# Based on the bioconda recipe:
#   https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mmseqs2

{% set commit = "fea8d2037312f66aa20b0976cda1ebeba2ce354f" %}
{% set version = "13-45111-post2-fea8d2037312f66aa20b0976cda1ebeba2ce354f" %}
{% set sha256 = "1cb092b578e38682064fdfa5908f52da6da0a6c4cf30767235d963de52b5f919" %}

package:
  name: mmseqs2
  version: {{ version|replace("-", ".")  }}

build:
  number: 0
  skip: True  # [win]

source:
  url: https://github.com/soedinglab/MMseqs2/archive/{{ commit }}.zip
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - perl
    - gawk
    - zlib
    - bzip2
  run:
    - wget
    - gawk
    - zlib
    - bzip2

test:
  commands:
    - mmseqs > /dev/null

about:
  home: https://github.com/soedinglab/mmseqs2
  license: GPLv3
  license_file: LICENSE.md
  summary: "MMseqs2: ultra fast and sensitive sequence search and clustering suite"

extra:
  identifiers:
    - doi:10.1038/nbt.3988
    - doi:10.1038/s41467-018-04964-5
    - doi:10.1093/bioinformatics/bty1057
    - doi:10.1101/2020.11.27.401018
    - biotools:mmseqs2
    - biotools:linclust
