# Based on the bioconda recipe:
#   https://github.com/bioconda/bioconda-recipes/tree/master/recipes/mmseqs2

{% set commit= "b0b8e85f3b8437c10a666e3ea35c78c0ad0d7ec2" %}
{% set version = "13-45111-post1-{{commit}}" %}
{% set sha256 = "0f2b192715a4f3011b34f179c2c6b50253537c6b82fbe75238aca66a7737860b" %}

package:
  name: mmseqs2
  version: {{ version|replace("-", ".")  }}

build:
  number: 0
  skip: True  # [win]

source:
  url: https://github.com/soedinglab/MMseqs2/archive/{{ commit }}.zip
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - perl
    - gawk
    - zlib
    - bzip2
  run:
    - wget
    - gawk
    - zlib
    - bzip2

test:
  commands:
    - mmseqs > /dev/null

about:
  home: https://github.com/soedinglab/mmseqs2
  license: GPLv3
  license_file: LICENSE.md
  summary: "MMseqs2: ultra fast and sensitive sequence search and clustering suite"

extra:
  identifiers:
    - doi:10.1038/nbt.3988
    - doi:10.1038/s41467-018-04964-5
    - doi:10.1093/bioinformatics/bty1057
    - doi:10.1101/2020.11.27.401018
    - biotools:mmseqs2
    - biotools:linclust
